DROP TABLE IF EXISTS CarTypes;
CREATE TABLE CarTypes (
name VARCHAR(15) PRIMARY KEY,
price FLOAT NOT NULL,
capacity INT NOT NULL);

DROP TABLE IF EXISTS Car;
CREATE TABLE Car (
carId INT PRIMARY KEY AUTO_INCREMENT,
carType VARCHAR(15) NOT NULL,
FOREIGN KEY (type) REFERENCES carTypes(type));

DROP TABLE IF EXISTS Reservations;
CREATE TABLE Reservations (
reservationId INT PRIMARY KEY AUTO_INCREMENT,
carId INT,
people INT,
startDate DATE,
endDate DATE,
FOREIGN KEY (carId) REFERENCES Car(carId)
)
