DROP TABLE IF EXISTS games;
CREATE TABLE games (
id INT PRIMARY KEY,
answer VARCHAR(4) NOT NULL,
isOngoing BOOLEAN NOT NULL);

DROP TABLE IF EXISTS rounds;
CREATE TABLE rounds (
gameId INT,
guess VARCHAR(4) NOT NULL,
guessTime VARCHAR(50) NOT NULL,
result VARCHAR(4) NOT NULL,
FOREIGN KEY (gameId) REFERENCES games(id));